# Generated by Django 4.1.1 on 2025-01-23 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the skill category (e.g., Cooking, Technology).', max_length=100, unique=True, verbose_name='Skill Category')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the subcategory name (e.g., Baking, Web Development).', max_length=100, verbose_name='Subcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='community.skillcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SkillListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a descriptive title for the skill (e.g., Mastering the Art of Baking).', max_length=200, verbose_name='Skill Title')),
                ('description', models.TextField(help_text='Provide a detailed description of the skill being offered.', verbose_name='Skill Description')),
                ('availability_start', models.DateTimeField(help_text="Specify the start date and time when you're available for sessions.", verbose_name='Start Availability')),
                ('availability_end', models.DateTimeField(help_text="Specify the end date and time when you're available for sessions.", verbose_name='End Availability')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='community.subcategory', verbose_name='Skill Subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Skill Sharer')),
            ],
            options={
                'verbose_name': 'Skill Listing',
                'verbose_name_plural': 'Skill Listings',
                'ordering': ['subcategory__category__name', 'subcategory__name', 'title'],
            },
        ),
    ]
