# Generated by Django 4.1.1 on 2025-01-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Provide a rating between 1 and 5.', verbose_name='Rating')),
                ('review', models.TextField(blank=True, help_text='Provide your feedback on the skill.', verbose_name='Review')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('skill_listing', models.ForeignKey(help_text='The skill listing being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='community.skilllisting', verbose_name='Skill Listing')),
                ('user', models.ForeignKey(help_text='The user providing the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Rating and Review',
                'verbose_name_plural': 'Ratings and Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('skill_listing', 'user')},
            },
        ),
    ]
