# Generated by Django 4.1.1 on 2025-01-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_ratingandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image related to the skill.', null=True, upload_to='skill_images/', verbose_name='Skill Image'),
        ),
    ]
