# Generated by Django 4.1.1 on 2025-01-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_messagethread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllisting',
            name='availability_end',
            field=models.TimeField(help_text="Specify the end time when you're available for sessions.", verbose_name='End Availability'),
        ),
        migrations.AlterField(
            model_name='skilllisting',
            name='availability_start',
            field=models.TimeField(help_text="Specify the start time when you're available for sessions.", verbose_name='Start Availability'),
        ),
    ]
