# Generated by Django 4.1.1 on 2025-01-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagethread',
            name='skill_listing',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageThread',
        ),
    ]
