# Generated by Django 4.1.1 on 2025-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_message_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllisting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Request Status'),
        ),
    ]
