# Generated by Django 4.1.1 on 2025-01-30 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0011_remove_skilllisting_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Request Status')),
                ('message', models.TextField(blank=True, help_text='Write a short message explaining why you are interested in this skill.', null=True, verbose_name='Request Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='community.skilllisting', verbose_name='Requested Skill')),
            ],
            options={
                'verbose_name': 'Skill Request',
                'verbose_name_plural': 'Skill Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
